class Character {
  String name;
  String rank;
  String type;
  String element;
  String faction;
  String hp;
  String atk;
  String def;
  String impact;
  String mastery;
  String proficiency;
  String image;

  Character({
    required this.name,
    required this.rank,
    required this.type,
    required this.element,
    required this.faction,
    required this.hp,
    required this.atk,
    required this.def,
    required this.impact,
    required this.mastery,
    required this.proficiency,
    required this.image,
  });
}

var listCharacter = [
  Character(
      name: 'Ellen Joe',
      rank: 'S',
      type: "attack",
      element: 'ice',
      faction: 'victoria housekeeping co',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/ellen.png'),
  Character(
      name: 'Grace Howard',
      rank: 'S',
      type: "anomaly",
      element: 'electric',
      faction: 'belobog heavy industries',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/grace.png'),
  Character(
      name: 'Koleda Belobog',
      rank: 'S',
      type: "stun",
      element: 'fire',
      faction: 'cunning hares',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/koleda.png'),
  Character(
      name: 'Von Lycaon',
      rank: 'S',
      type: "stun",
      element: 'ice',
      faction: 'victoria housekeeping co',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/lycaon.png'),
  Character(
      name: 'Nekomiya Mana',
      rank: 'S',
      type: "attack",
      element: 'physical',
      faction: 'cunning hares',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/nekomata.png'),
  Character(
      name: 'Alexandrina Sebastiane',
      rank: 'S',
      type: "support",
      element: 'electric',
      faction: 'victoria housekeeping co',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/rina.png'),
  Character(
      name: 'Anby Demara',
      rank: 'A',
      type: "stun",
      element: 'electric',
      faction: 'cunning hares',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/anby.png'),
  Character(
      name: 'Anton Ivanov',
      rank: 'A',
      type: "attack",
      element: 'electric',
      faction: 'belobog heavy industries',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/anton.png'),
  Character(
      name: 'Ben Bigger',
      rank: 'A',
      type: "defense",
      element: 'fire',
      faction: 'belobog heavy industries',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/ben.png'),
  Character(
      name: 'Billy Kid',
      rank: 'A',
      type: "attack",
      element: 'physical',
      faction: 'cunning hares',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/billy.png'),
  Character(
      name: 'Corin Whick',
      rank: 'A',
      type: "attack",
      element: 'physical',
      faction: 'victoria housekeeping co',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/corin.png'),
  Character(
      name: 'Nicole Demara',
      rank: 'A',
      type: "support",
      element: 'ether',
      faction: 'cunning hares',
      hp: '617',
      atk: '135',
      def: '49',
      impact: '93',
      mastery: '94',
      proficiency: '93',
      image: 'assets/images/character/nicloe.png'),
];
